GENERAL:
  experiment: teeth3ds
  seed: 0

DATA:
  # data path
  root_dir: F:/dataset/Teeth3DS/data # path of simplified meshes and ground truth
  split_dir: F:/dataset/Teeth3DS/split
  pred_dir: F:/dataset/Teeth3DS/results/dgcnn # path of coarse segmentation results
  # batch_size per gpu
  batch_size: 2
  # sample
  num_points: 4096 # must < size of mesh.vertices
  # augmentation
  augmentation: True
  # upper/lower

STRUCTURE:
  k: 20
  input_channels: 3
  n_edgeconvs_backbone: 5
  emb_dims: 1024
  global_pool_backbone: avg   # max or avg
  norm: instance
  use_stn: True # spatial transformer network
  dynamic: True
  dropout: 0.

TRAIN:
  max_epochs: 100
  weight_decay: 0.0001
  load_from_checkpoint:
  resume_from_checkpoint:

  # one cycle lr scheduler
  lr_max: 0.001
  pct_start: 0.1    # percentage of the cycle spent increasing lr
  div_factor: 25    # determine the initial lr (lr_max / div_factor)
  final_div_factor: 1e4   # determine the final lr (lr_max / final_div_factor)
  start_epoch: 0

  train_file: training_upper.txt  # training_upper.txt or training_lower.txt or training_all.txt
  train_workers: 1

  val_workers: 1
  val_file: testing_upper.txt  # testing_upper.txt or testing_lower.txt or testing_all.txt

  test_workers: 1
  test_file: testing_upper.txt  # testing_upper.txt or testing_lower.txt testing_all.txt